### ISSUE TITLE
Tutorials not available

### ISSUE THREAD

**Issue by RaoOfPhysics** [ropensci/roweb3#176]
Hi folks,

Looks like the `/tutorials` section on https://ropensci.org is broken, redirecting to https://docs.ropensci.org/.

I noticed when I was poking around the `arXiv` docs and came across a link to https://ropensci.org/tutorials/arxiv_tutorial/. I also tried a bunch of others – https://duckduckgo.com/?q=site%3Aropensci.org%2Ftutorials – and also just https://ropensci.org/tutorials/.

Thanks!
Achintya

**Comment by maelle** [comment]
Thank you!

We stopped maintaining the tutorials as they were often the same content as the vignettes found in the pkgdown websites, and it's easier for the package maintainers to edit the docs in their package repo rather than in a central place.

Now hopefully the broken links will disappear from the package docs and from search engines!

**Comment by RaoOfPhysics** [comment]
Noted, @maelle. Perhaps worth maintaining a static page at https://ropensci.org/tutorials with that information for all the links pointing to it?

Thanks for the great work with the project!

**Comment by maelle** [comment]
Excellent idea @RaoOfPhysics, thank you for the feedback!
