### ISSUE TITLE
Nit-picky blog details with single quotes

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#367]
For some reason, when building the blog from text in index.md which contains a word in single quotes (e.g.,  `'re-indexed'`), the output has two different types of quotes:

![image](https://user-images.githubusercontent.com/14676081/181299181-edac0bec-5e42-4897-b8d1-6b705349be08.png)

Is this expected? Fixable? Or should I just a) ignore it, or b) use double quotes?

(Example from https://github.com/ropensci/roweb3/pull/364/files#diff-82cedd925b2655de190f7500c5c2862998d459465aa457e2e1a62ce1a5f0a3a6R32)

**Comment by maelle** [comment]
The transformation (the part that works well) is due to the typography extension that's turned on for Hugo here and that behaves like https://daringfireball.net/projects/smartypants/ Turning it off would mean "--" does not become a long dash so that would not be good.

Now why does it not transform both quotes, answer below:

After experimenting it turns out that if you type `'reindexed'` it looks good but the problem is the hyphen that apparently throws something off? Double quotes look better. See screenshot of my experiments below

![image](https://user-images.githubusercontent.com/8360597/181435793-06c44fc1-0a59-46ef-8d21-5b99ff473997.png)

**Comment by maelle** [comment]
And of course we can't ignore this, once you see it it's impossible to forget :joy: So I'd suggest going for the double quotes as you suggested yourself.

**Comment by steffilazerte** [comment]
Hahah, thanks for going down the rabbit hole for me!

**Comment by maelle** [comment]
The real rabbit hole, that I did not go down, would be to find out whether this is a feature or a bug. I won't try to find out :wink:
