### ISSUE TITLE
Link r-universe technotes to github discussions

### ISSUE THREAD

**Issue by jeroen** [ropensci/roweb3#547]
We decided last year to move discussions about r-universe to github discussions. However r-universe technotes still have the link to start a discussion on discourse, and some people do: https://ropensci.org/blog/2023/04/03/cran-to-git/

Can we change the "Start discussion" link for r-universe technotes to point to https://github.com/r-universe-org/help/discussions ?

**Comment by maelle** [comment]
Yes it's doable. Let me assess the request better with a few questions :smile_cat: 

- Would we do this for all posts tagged R-universe or only those where you are an author? 
- What to do about old posts that already got comments on Discourse? Still remove the link to Discourse?
- Should the link be to the discussions page, or should you create a topic, store its ID in the post metadata, so that the link would be to the post discussion? I thought of "intent URLs" (like for Twitter/LinkedIn/Mastodon etc) but I don't think it exists for GitHub discussions; and we'd end up with duplicate topics.

**Comment by jeroen** [comment]
Let's keep it simple. Maybe we can use the same rule that we use for displaying the r-universe intro banner ?

A single link to the discussions page is good, no need to have tight integration.
