### ISSUE TITLE
Comm call for champions program is missing names

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb3#610]
https://ropensci.org/commcalls/july2023-championprogram/

<img width="860" alt="image" src="https://github.com/ropensci/roweb3/assets/138494/11562a25-a0a6-489c-81b6-eb34452e54d5">

**Comment by maelle** [comment]
@yabellini from looking at https://ropensci.org/commcalls/jan2023-targets/ it seems this wasn't a problem before because the bios started with the person's name. How would you prefer to solve this?

- rephrase/complement the bios the speakers had provided.
- tweak the layout somehow to have the name appear independently of what's in the bio?

**Comment by yabellini** [comment]
It would be nice to use the name in the YAML below the pictures.

**Comment by maelle** [comment]
ok, let me make a PR

**Comment by maelle** [comment]
(and thanks @karthik for reporting! :pray: )
