### ISSUE TITLE
Metadata for Zotero

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#656]
From a comment by @mfenner

https://www.zotero.org/support/dev/exposing_metadata

**Comment by mfenner** [comment]
For content with a DOI, it is easiest to just give the DOI to Zotero. And keep in mind that the Zotero web translators can either collect the DOI from a single blog post, or multiple DOIs from a listing or query result with a UI to pick the posts/articles you want to import.

**Comment by maelle** [comment]
>  And keep in mind that the Zotero web translators can either collect the DOI from a single blog post, or multiple DOIs from a listing or query result with a UI to pick the posts/articles you want to import.

Could you clarify what this means in terms of metadata to be added to a website?

**Comment by mfenner** [comment]
Since Rogue Scholar is collecting a lot of metadata and uses them for DOI registration, Zotero can get them via the Crossref API, and does this automatically if the web translator sees a DOI. And the UI looks like this (from https://rogue-scholar.org/posts?page=1&query=ropensci):

<img width="1316" alt="Bildschirmfoto 2023-10-10 um 14 12 35" src="https://github.com/ropensci/roweb3/assets/23151/e443623c-2416-4c39-a1ef-ec60493985be">

**Comment by maelle** [comment]
I added DOI to the metadata, if I followed correctly that's enough
