### ISSUE TITLE
Add new mentors to champions webpage

### ISSUE THREAD

**Issue by yabellini** [ropensci/roweb3#673]
- How should we list the two cohorts together?
@maelle any idea?

**Comment by maelle** [comment]
In https://github.com/ropensci/roweb3/pull/595/files we added the years (for instance "champion 2022-2023") so that we could simply add the mentors and champions of the second cohorts to the files.
Please add the new champions/mentors before the first cohort in the JSON files, so that they appear first on the webpage.
Later we could consider making the order random.
